name: Deploy to AWS Lambda
on:
  push:
    branches:
      - none

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2
  DOCKER_IMAGE_URI: ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }}

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4

      - name: configure AWS Credentials
        uses: aws-actions/configure-aws-credentials/@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-assume: ${{ secrets.OIDC_ROLE }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - run: ./gradle build --no-daemon

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker image to Amazon ECR
        run: |
          docker build -t $DOCKER_IMAGE_URI .
          docker push $DOCKER_IMAGE_URI

      - name: Deploy to AWS Lambda
        env:
          LAMBDA_FUNCTION_NAME: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
        run: |
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri $DOCKER_IMAGE_URI --region $AWS_REGION